#**Install Libraries**

In [ ]:
!python -m pip install copernicusmarine

#**Getting Data Sea Level Dataset from Copernicusmarine**

Note: You will need Copernicusmarine Account to run the script below

In [ ]:
import copernicusmarine

# Using the East Coast Coordinate Range( Longtitude and Latitude)
min_lat = 25
max_lat = 44.63
min_long = -102
max_long = -60

# List Variables want to retrieve
var_list = ["adt", "sla", "ugos", "ugosa", "vgos", "vgosa"]

# Date Range
startDate = "2017-01-01"
endDate = "2020-12-31"

# Load dataframe
request_dataframe = copernicusmarine.read_dataframe(
    dataset_id = "c3s_obs-sl_glo_phy-ssh_my_twosat-l4-duacs-0.25deg_P1D",
    minimum_longitude = min_long,
    maximum_longitude= max_long,
    minimum_latitude= max_lat,
    maximum_latitude= min_lat,
    variables = var_list,
    start_datetime = startDate,
    end_datetime = endDate
)

# Print loaded dataset information
print(request_dataframe)

In [ ]:
# Filter Data
seaLevel_df = request_dataframe
seaLevel_df.dropna(inplace=True)

In [ ]:
# For the Midpoint Report
# Filter the DataFrame to include only the specified dates
target_dates = ['2017-01-01', '2018-01-01', '2019-01-01', '2020-01-01']
seaLevel_df = seaLevel_df.loc[target_dates]

In [ ]:
seaLevel_df

#**Apply States to Sea Level Dataset**

In [ ]:
import pandas as pd

# Get the States Latitude and Longtitude Range Dataset
stateDF = pd.read_csv('USstates_Lat&Long.csv')

This script is the longest script. It loops through every row in seaLevel_df dataframe. Therefore, the bigger the dataframe, the longer it will take to run this section. The code could time out.

In [ ]:
# Function to assign states based on latitude and longitude
def get_state(latitude, longitude):
    for index, row in stateDF.iterrows():
        if (row['Lat_min'] <= latitude <= row['Lat_max']) and (row['Long_min'] <= longitude <= row['Long_max']):
            return row['State']
    return None

# Apply the function to create a new 'State' column in df
seaLevel_df['State'] = seaLevel_df.apply(lambda x: get_state(x.name[1], x.name[2]), axis=1)

#Filter
seaLevel_df = seaLevel_df.dropna(subset=['State'])

In [ ]:
#Export Final Data
seaLevel_df.to_excel('test.xlsx')

#For Tableau Visulization specifically

Minh Dao script for Tableau:

In [ ]:
# Get rid of index
seaLevel_df.reset_index(inplace=True)
seaLevel_df.drop(columns=['index'], inplace=True)

# Create year col
seaLevel_df['year'] = seaLevel_df['time'].dt.year

# Export
seaLevel_df.to_excel('test.xlsx')